experiment_name: umap_hyperparameters_on_kuhar.standartized_balanced_starting_with_30.60.90...300
search_space:
  umap_ncomp:
    tune_function: randint
    tune_parameters: [2, 360]
  umap_spread:
    tune_function: randint
    tune_parameters: [1, 10]
  umap_mdist:
    tune_function: uniform
    tune_parameters: [0.0, 0.99]
  umap_neigh:
    tune_function: randint
    tune_parameters: [2, 201]
initial_params:
  - umap_ncomp: 30
    umap_spread: 1
    umap_mdist: 0.1
    umap_neigh: 15
  - umap_ncomp: 60
    umap_spread: 1
    umap_mdist: 0.1
    umap_neigh: 15
  - umap_ncomp: 90
    umap_spread: 1
    umap_mdist: 0.1
    umap_neigh: 15
  - umap_ncomp: 120
    umap_spread: 1
    umap_mdist: 0.1
    umap_neigh: 15
  - umap_ncomp: 150
    umap_spread: 1
    umap_mdist: 0.1
    umap_neigh: 15
  - umap_ncomp: 200
    umap_spread: 1
    umap_mdist: 0.1
    umap_neigh: 15
  - umap_ncomp: 300
    umap_spread: 1
    umap_mdist: 0.1
    umap_neigh: 15