experiment_name: test30...300
resources:
  gpu_usage: 0.0
  cpu_usage: 1.0
search_space:
  umap_ncomp:
    tune_function: randint
    tune_parameters: [2, 360]
    route: reducer/kwargs/n_components
  umap_spread:
    tune_function: randint
    tune_parameters: [1, 10]
    route: reducer/kwargs/spread
  umap_mdist:
    tune_function: uniform
    tune_parameters: [0.0, 2]
    route: reducer/kwargs/min_dist
  umap_neigh:
    tune_function: randint
    tune_parameters: [2, 201]
    route: reducer/kwargs/n_neighbors
initial_params:
  - umap_ncomp: 30
    umap_spread: 1
    umap_mdist: 0.1
    umap_neigh: 15
  - umap_ncomp: 60
    umap_spread: 1
    umap_mdist: 0.1
    umap_neigh: 15
  - umap_ncomp: 90
    umap_spread: 1
    umap_mdist: 0.1
    umap_neigh: 15
  - umap_ncomp: 120
    umap_spread: 1
    umap_mdist: 0.1
    umap_neigh: 15
  - umap_ncomp: 150
    umap_spread: 1
    umap_mdist: 0.1
    umap_neigh: 15
  - umap_ncomp: 200
    umap_spread: 1
    umap_mdist: 0.1
    umap_neigh: 15
  - umap_ncomp: 300
    umap_spread: 1
    umap_mdist: 0.1
    umap_neigh: 15