estimators:
-   algorithm: RandomForest
    kwargs:
        n_estimators: 100
    name: randomforest-100
    num_runs: 10
-   algorithm: KNN
    kwargs:
        n_neighbors: 5
    name: KNN-5
    num_runs: 1
-   algorithm: SVM
    kwargs:
        C: 1.0
        kernel: rbf
    name: SVM-rbf-C1.0
    num_runs: 1
extra:
    in_use_features:
    - accel-x
    - accel-y
    - accel-z
    - gyro-x
    - gyro-y
    - gyro-z
    reduce_on: all
    save_reducer: false
    scale_on: train
reducer_dataset:
- realworld_thigh.standartized_balanced_patrick[train]
test_dataset:
- realworld_thigh.standartized_balanced_patrick[validation]
train_dataset:
- realworld_thigh.standartized_balanced_patrick[train]
transforms: []
version: '1.0'
